### ISSUE TITLE
Module fails to update .source_code_hash in aws_lambda_function.this when TF_RECREATE_MISSING_LAMBDA_PACKAGE is false

### ISSUE THREAD

**Issue by aldenAMS** [terraform-aws-modules/terraform-aws-notify-slack#148]
## Description

Terraform apply failing with Error: Provider produced inconsistent final plan after updates to module causing archive to be rebuilt when TF_RECREATE_MISSING_LAMBDA_PACKAGE is set to 'false'

## Versions

 - Terraform: 1.0.8

 - Provider(s): 
 - hashicorp/null v3.1.0
- hashicorp/external v2.1.0
- hashicorp/aws v3.62.0
- hashicorp/template v2.2.0
- hashicorp/local v2.1.0
- hashicorp/random v3.1.0

 - Module: 4.17.0 -> Module 4.18.0

## Reproduction

 - Set environment variable TF_RECREATE_MISSING_LAMBDA_PACKAGE='false'
 - Run terraform apply using module version 4.17
 - Delete local cache including all terraform generated files and build directory
 - Change module version to 4.18
 - Run terraform apply

### Code Snippet to Reproduce
```
terraform {
  required_version = ">= 1.0.0, < 2.0.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.27"
    }
  }
}

provider "aws" {
  profile = "default"
  region  = "us-west-1"
}

terraform {
  backend "s3" {
    bucket         = "<bucket name>"
    key            = "aws-notify-slack-test"
    region         = "us-west-1"
  }
}

module "notify_slack_test" {
  source               = "terraform-aws-modules/notify-slack/aws"
  version              = "4.18"

  sns_topic_name       = "terraform-aws-modules-notify-slack-test"
  lambda_function_name = "terraform-aws-modules-notify-slack-test"
  slack_webhook_url    = var.slack_webhook_url
  slack_channel        = "test"
  slack_username       = "AWS (terraform-aws-modules-notify-slack-test)"
  slack_emoji          = ":warning:"
  create               = true
  create_sns_topic     = true
}
```

## Expected behavior
Terraform should apply changes as expected

## Actual behavior
Apply fails to update module.lambda.aws_lambda_function.this[0]

### Terminal Output Screenshot(s)
![image](https://user-images.githubusercontent.com/52429324/137203311-bb541afa-92d3-4558-bc4e-5d83904927e6.png)

**Comment by llamahunter** [comment]
I think a variable was added for this recently in the lambda module that makes this env variable unnecessary? https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/181

**Comment by antonbabenko** [comment]
This issue has been resolved in version 4.23.0 :tada:

**Comment by UsaninMax** [comment]
issue is not resolved 
![image](https://user-images.githubusercontent.com/2196217/151959463-9d8bf8cb-9e9e-473f-a4ef-23418276b38f.png) 
![image](https://user-images.githubusercontent.com/2196217/151959508-b2d622ea-f44f-49af-b367-fd4faa3d22bf.png)
