### ISSUE TITLE
Resource gets modified when absolute path to module changes

### ISSUE THREAD

**Issue by brainsik** [terraform-aws-modules/terraform-aws-notify-slack#6]
Hello. It appears the absolute path of the module is encoded in the state such that using the _exact same_ Terraform in two different paths produces state changes instead of producing no changes at all.

For example:

```
  ~ module.notify_slack_engineering.aws_lambda_function.notify_slack
      filename:           "/Users/foo/src/project/.terraform/modules/d040de6279d8f75cc8478e75c8a39e23/terraform-aws-modules-terraform-aws-notify-slack-5cdd039/functions/notify_slack.zip" => "/Users/bar/src/project/.terraform/modules/d040de6279d8f75cc8478e75c8a39e23/terraform-aws-modules-terraform-aws-notify-slack-5cdd039/functions/notify_slack.zip"
      last_modified:      "2018-04-17T23:20:20.668+0000" => <computed>
```

This is problematic for having different users running `terraform plan` locally while doing development work as they end up getting this false change in their output.

Is there a way to use a relative path?

**Comment by lorengordon** [comment]
Probably safe to modify the resource in main.tf to ignore changes to the filename. It ought to generate changes if the sha changes, anyway...

**Comment by antonbabenko** [comment]
Fixed in [v1.3.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/v1.3.0)

**Comment by brainsik** [comment]
This is still a problem due to the "last_modified" attribute which is based on when the local file was modified. This means its different for different users depending on when they ran `terraform init`. I'll make  PR shortly.
